CLASS z_aspec_test_options DEFINITION
  PUBLIC ABSTRACT
  FOR TESTING RISK LEVEL HARMLESS DURATION SHORT.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS z_aspec_test_options IMPLEMENTATION.
ENDCLASS.
